name: ai-bats
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tabpfn-extensions
  - pip
  - pip:
      - tabpfn-extensions[all] @ git+https://github.com/PriorLabs/tabpfn-extensions.git