name: aibats
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - umap-learn
  - matplotlib
  - seaborn
  - tabpfn
  - scipy
  - shap
  - pip
  - pip:
      - tabpfn
